modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
    modId="datadriven"
    version="${file.jarVersion}"
    displayName="Data-Driven"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/data-driven"
    logoFile="logo.png"
    credits="Thanks for supporting me by using my mods to do cool shit"
    authors="Ewy"
    description='''Generate content for Minecraft using data-driven json files!'''

[[dependencies.datadriven]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.datadriven]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
